---

- 
- hosts: localhost
  
  gather_facts: false
  
  tasks:
  - name: "Check output locally"
    
  debug:
      msg: "Starting ansible job"


- hosts: cicd.jenkins.nml.com
  
  become: true
  
  become_user: root
  
  gather_facts: true
  
  remote_user: cdtoolsp
  
  roles:
 jenkins 
